dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-05/run.sh |
  bash
install:
- sudo pip install ansible==2.6.1
- sudo pip install ansible-lint==3.4.23
- wget -O tflint.zip https://github.com/wata727/tflint/releases/download/v0.7.0/tflint_linux_amd64.zip && sudo unzip -d /usr/bin/ tflint.zip
- wget -O packer.zip https://releases.hashicorp.com/packer/1.2.5/packer_1.2.5_linux_amd64.zip && sudo unzip -d /usr/bin/ packer.zip
- wget -O terraform.zip https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip && sudo unzip -d /usr/bin/ terraform.zip
- touch ~/.ssh/appuser
- touch ~/.ssh/appuser.pub
script:
- cd ansible && ansible-lint -x ANSIBLE0011 -v playbooks/*.yml
- cd ../ && find packer -name "*.json" -type f -print0 | xargs -0 -n1 packer validate -var-file=packer/variables.json.example
- cd terraform/stage && terraform init -backend=false && tflint --var-file=terraform.tfvars.example && terraform validate -var-file=terraform.tfvars.example
- cd ../prod && terraform init -backend=false && tflint --var-file=terraform.tfvars.example && terraform validate -var-file=terraform.tfvars.example
notifications:
  slack:
    rooms:
      secure: raxtZrDrkEEA4k3e7GQ/wXVR758Me2caKXaFUG9qEUJ6I9Q+3UpN3pfYBKcM577I7Ur2/riRWuLHWf9gDKs+bw6P3oFRyZu1BryLJcii+b7+VGeAmZCEW3weCfWHOzE1TNHe9GHtRaMOoqBeMXmXBZJCha32JRA/J+PyXg2zLXLW4uVCuKys+HW3X+j8le44JfXFqKXcW5oNU19iqLJKsTvg9XktQI6IG92zNg1x7sWqzyx4I/4QraBBvjfI5jbJnJk4qaKiTtNh+9y7luOxLdDvxU0+jxqY92CAqopIFffeLTU9+GBOzy/y5u5d1MYwlerZDjnK+ga4fg919xi0Jimkon0671lcIszmYtFCtP6xfOtcVjKfv83W/CRnd13nSDrdY8LU2ofkIAONtO+Ip+Fjz4F/Gnn95TFprSFRJBXxqCESs5snC69S+9DuKIMTNLd0htgNLRsoJBPHQKHnP1tpj+up8Nu9SyHG0Om0IEYw0eyq9Eir+u27DWcVTz7iAWsBWojRWewuaRUQws3IqC/6HSlstrnh6PJIZKHhw8xkyYY9x6IyE5I5Pb46ruGdjWv6l/wwPnzPkUsTXtju44C8sfgEopJuU/rHT6O/YcvMxJUvnkNyHQttYU9CmXDtNIpp/vn+/dNd7k2hfO5ynZ6GjfZei9L7iM48QzIHG/4=
